[project]
name = "tides_spextractor"
dynamic = ["version"]
license = {text = "BSD 3-Clause"}
authors = [
  {name = "Harry Addison", email = "ha00871@surrey.ac.uk"}]
keywords = ["TiDES", "Spectra"]
description = "TiDES SN spectral analysis"
readme = {file = "README.rst", content-type = "text/x-rst"}
dependencies = ["astropy", "extinction", "matplotlib", "numpy", "PyYAML"]

[project.optional-dependencies]
test = ["pytest", "pytest-doctestplus"]
doc = ["setuptools_scm", "sphinx", "sphinx-argparse", "sphinx-astropy"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["tides_spextractor*"]
namespaces = true

[tool.setuptools_scm]
write_to = "tides_spextractor/version.py"

[tool.pytest.ini_options]
testpaths = ["tides_spextractor"]
addopts = "--doctest-modules"

[tool.coverage.run]
source = ["tides_spextractor"]
